#! /usr/bin/env python
# -----------------------------------------------------------------------------
#    Kakuch - Traffic wrapper application
#    Copyright (C) 2013 Sameer Rahmani <lxsameer@gnu.org>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License along
#    with this program; if not, write to the Free Software Foundation, Inc.,
#    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
# -----------------------------------------------------------------------------

from kakuch.clients import DispatchClient


default_config = {
    "server": True,
    "remote_host": "127.0.0.1",
    "remote_port": 9100,
    "bind_port": 9100,
}


a = DispatchClient(server_host="127.0.0.1",
                   server_port="7777", my_host="127.0.0.1",
                   my_port="8888", sslkey="ssl/client/client.key",
                   sslcert="ssl/client/client.crt",
                   cacert="ssl/CA.crt")
a.run()
